name: complex_ui
description: A new Flutter project.

publish_to: 'none'

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/meditation/
    - assets/travel/
    - assets/travel/place/
    - assets/furniture/fur_icon/
    - assets/furniture/fur_img/
    - assets/mydoc/doc_icon/
    - assets/mydoc/icon/
    - assets/car/car_icon/
    - assets/car/car_img/
    - assets/cartoon/cartoon_img/
    - assets/cartoon/cartoon_icon/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: TitleFont
      fonts:
        - asset: assets/cartoon/cartoon_font/title_font.ttf
        - asset: assets/cartoon/cartoon_font/title_font1.ttf
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
